version: '2'

services:
    jws-server:
        container_name: cscb869
        build:
            context: cscb869
            dockerfile: Dockerfile_Debug
        environment:
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            # args:
            #     - DB_DATABASE=${DB_DATABASE}
            #     - DB_USERNAME=${DB_USERNAME}
            #     - DB_PASSWORD=${DB_PASSWORD}
        image: cscb869:latest
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
        volumes: 
            - ./CSCB869:/app
    hospital-mysql-db:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'hospitaldb:/databases/cscb869/'
        networks:
            - spring-cloud-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s  

volumes:
    hospitaldb:
        driver: local

networks:
    spring-cloud-network:
        driver: bridge


